package models;
// Generated 01-13-2023 07:20:03 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable{

    private int id;
    private String usuario;
    private String clave;
    private Date creacion;

    public Usuarios() {
    }

    public Usuarios(int id, String usuario, String clave) {
        this.id = id;
        this.usuario = usuario;
        this.clave = clave;
    }
    
    public Usuarios(int id, String usuario, String clave, Date creacion) {
       this.id = id;
       this.usuario = usuario;
       this.clave = clave;
       this.creacion = creacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Date getCreacion() {
        return this.creacion;
    }
    
    public void setCreacion(Date creacion) {
        this.creacion = creacion;
    }
    
}


